// 'use client'
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import './globals.css'
import LayoutWrapper from '@/components/LayoutWrapper'

export const metadata = {
  title: 'LMS App',
  description: 'Learning Management System',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  )
}



// import './globals.css'
// import { useState } from 'react'

// export const metadata = {
//   title: 'LMS App',
//   description: 'Learning Management System',
// }

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   const [isSidebarOpen, setIsSidebarOpen] = useState(true)

//   return (
//     <html lang="en">
//       <body className="flex flex-col min-h-screen">

//         {/* Header */}
//         <header className="w-full bg-gray-800 text-white px-6 py-4 flex justify-between items-center">
//           <h1 className="text-xl font-semibold">My LMS</h1>
//           <nav className="space-x-6">
//             <a href="#" className="hover:underline">Dashboard</a>
//             <a href="#" className="hover:underline">Courses</a>
//             <a href="#" className="hover:underline">Profile</a>
//           </nav>
//         </header>

//         {/* Layout Content Area */}
//         <div className="flex flex-1">
//           {/* Sidebar */}
//           <aside className={`bg-gray-100 h-full p-4 transition-all duration-300 ${isSidebarOpen ? 'w-48' : 'w-16'}`}>
//             <button
//               onClick={() => setIsSidebarOpen(!isSidebarOpen)}
//               className="text-sm text-gray-600 mb-4"
//             >
//               {isSidebarOpen ? 'Collapse' : 'Expand'}
//             </button>
//             {isSidebarOpen && (
//               <ul className="space-y-2 text-sm">
//                 <li>Item 1</li>
//                 <li>Item 2</li>
//                 <li>Item 3</li>
//               </ul>
//             )}
//           </aside>

//           {/* Main Content */}
//           <main className="flex-1 p-6 bg-white">
//             {children}
//           </main>
//         </div>

//         {/* Footer */}
//         <footer className="w-full bg-gray-200 text-center py-4 text-sm text-gray-700 mt-auto">
//           &copy; 2025 My LMS. All rights reserved.
//         </footer>

//       </body>
//     </html>
//   )
// }



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
